# Configuration for generate_analysis.py
# Place this file in the same directory as the script

# Folder settings
INPUT_FOLDER: "~/Documents/Notes"      # Main notes folder

# Folders to exclude (list format - add as many as needed)
EXCLUDE_FOLDERS:
  - "~/Documents/Notes/AI"
  - "~/Documents/Notes/Clippings"

# Daily notes settings
DAILY_NOTES_FOLDER: "~/Documents/Notes/Journal/Daily Notes"   # Where daily notes are stored
DAILY_NOTE_TITLE_FORMAT: "%Y-%m-%d"                         # Format for daily note filenames
DAILY_NOTE_TEMPLATE_PATH: "~/Documents/Notes/Extras/Templates/Template Daily.md"
DAILY_NOTE_TEMPLATE: "---\ntitle: {{date}}\ncreated: {{date}}\n---\n\n# {{date:dddd, MMMM D, YYYY}}\n\n## Tasks\n\n## Notes\n\n# Yesterday's Analysis\n"

# Analysis settings
ANALYSIS_HEADER: "# Yesterday's Analysis"                  # Header where analysis will be appended

# LLM Provider settings
LLM_PROVIDER: "ollama"                                      # Options: "ollama" or "openai"

# Ollama settings
OLLAMA_MODEL: "gemma3:12b"                                  # Model to use
OLLAMA_SERVER_ADDRESS: "http://localhost:11434"         # Ollama server address
OLLAMA_CONTEXT_WINDOW: 32000                                # Context window size

# OpenAI settings (used when LLM_PROVIDER is "openai")
OPENAI_API_KEY: ""                                          # Your OpenAI API key (required for OpenAI)
OPENAI_MODEL: "gpt-4"                                       # OpenAI model to use
OPENAI_MAX_TOKENS: 4000                                     # Maximum tokens for responses
